import { Faculty, Paper } from './types';

export const FACULTIES: Faculty[] = [
  {
    id: 'science',
    name: 'Computer Science Department',
    description: 'Pioneering breakthroughs in computation, logic, artificial intelligence, and software engineering.',
    papers: 60,
    departments: 1,
    icon: 'science',
    color: 'secondary',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9d38452a6?auto=format&fit=crop&q=80&w=800',
    featured: true
  }
];

export const RECENT_PAPERS: Paper[] = [
  // ── 100 LEVEL (15 Papers) ───────────────────────────────────
  {
    id: 'csc-101',
    title: 'Introduction to Computer Science',
    courseCode: 'CSC 101',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 342,
    pages: 6,
    date: 'Recently added',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-05T18:00:00.000Z',
  },
  {
    id: 'csc-102',
    title: 'Introduction to Problem Solving',
    courseCode: 'CSC 102',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 215,
    pages: 8,
    date: 'Recently added',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-05T17:30:00.000Z',
  },
  {
    id: 'mth-101',
    title: 'Elementary Mathematics I',
    courseCode: 'MTH 101',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 512,
    pages: 5,
    date: 'Recently added',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-05T17:00:00.000Z',
  },
  {
    id: 'mth-102',
    title: 'Elementary Mathematics II',
    courseCode: 'MTH 102',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 418,
    pages: 7,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T16:00:00.000Z',
  },
  {
    id: 'phy-101',
    title: 'General Physics I',
    courseCode: 'PHY 101',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 302,
    pages: 6,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T15:30:00.000Z',
  },
  {
    id: 'phy-102',
    title: 'General Physics II',
    courseCode: 'PHY 102',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 284,
    pages: 9,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T15:00:00.000Z',
  },
  {
    id: 'chm-101',
    title: 'General Chemistry I',
    courseCode: 'CHM 101',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 198,
    pages: 8,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T14:30:00.000Z',
  },
  {
    id: 'chm-102',
    title: 'General Chemistry II',
    courseCode: 'CHM 102',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 145,
    pages: 10,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T14:00:00.000Z',
  },
  {
    id: 'csc-120',
    title: 'Computer Application Packages',
    courseCode: 'CSC 120',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 489,
    pages: 11,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Web%20Design%20and%20Programming.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T12:00:00.000Z',
  },
  {
    id: 'gst-101',
    title: 'Use of English',
    courseCode: 'GST 101',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 602,
    pages: 4,
    date: '1 week ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: 'gst-102',
    title: 'Philosophy and Logic',
    courseCode: 'GST 102',
    level: '100 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 535,
    pages: 5,
    date: '1 week ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-30T09:30:00.000Z',
  },
  {
    id: 'csc-111',
    title: 'Introduction to Computing',
    courseCode: 'CSC 111',
    level: '100 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 390,
    pages: 8,
    date: '2 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-23T10:00:00.000Z',
  },
  {
    id: 'mth-111',
    title: 'College Algebra',
    courseCode: 'MTH 111',
    level: '100 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 480,
    pages: 6,
    date: '2 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-23T09:00:00.000Z',
  },
  {
    id: 'csc-191',
    title: 'Practical Computing',
    courseCode: 'CSC 191',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 275,
    pages: 12,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T15:00:00.000Z',
  },
  {
    id: 'gst-111',
    title: 'Library Skills',
    courseCode: 'GST 111',
    level: '100 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 340,
    pages: 5,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T14:30:00.000Z',
  },

  // ── 200 LEVEL (15 Papers) ───────────────────────────────────
  {
    id: 'csc-201',
    title: 'Computer Programming I',
    courseCode: 'CSC 201',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 824,
    pages: 8,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T10:00:00.000Z',
  },
  {
    id: 'csc-202',
    title: 'Data Structures',
    courseCode: 'CSC 202',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 654,
    pages: 12,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T09:30:00.000Z',
  },
  {
    id: 'csc-203',
    title: 'Discrete Structures',
    courseCode: 'CSC 203',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 412,
    pages: 9,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T15:00:00.000Z',
  },
  {
    id: 'csc-205-object-oriented-programming',
    title: 'Object Oriented Programming',
    courseCode: 'CSC 205',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 935,
    pages: 15,
    date: '2 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-23T10:00:00.000Z',
  },
  {
    id: 'csc-206',
    title: 'Introduction to Digital Design',
    courseCode: 'CSC 206',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 387,
    pages: 8,
    date: '2 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-23T08:30:00.000Z',
  },
  {
    id: 'csc-208',
    title: 'Assembly Language Programming',
    courseCode: 'CSC 208',
    level: '200 Level',
    year: '2022/2023',
    semester: '2nd Semester',
    downloads: 290,
    pages: 10,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T11:00:00.000Z',
  },
  {
    id: 'mth-201',
    title: 'Linear Algebra I',
    courseCode: 'MTH 201',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 410,
    pages: 6,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T10:30:00.000Z',
  },
  {
    id: 'mth-202',
    title: 'Linear Algebra II',
    courseCode: 'MTH 202',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 324,
    pages: 7,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T16:00:00.000Z',
  },
  {
    id: 'sta-201',
    title: 'Probability & Statistics I',
    courseCode: 'STA 201',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 560,
    pages: 8,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T15:30:00.000Z',
  },
  {
    id: 'sta-202',
    title: 'Probability & Statistics II',
    courseCode: 'STA 202',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 489,
    pages: 9,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T15:00:00.000Z',
  },
  {
    id: 'csc-211',
    title: 'Foundation of Sequential Systems',
    courseCode: 'CSC 211',
    level: '200 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 305,
    pages: 8,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T12:00:00.000Z',
  },
  {
    id: 'csc-221',
    title: 'Computer Electronics',
    courseCode: 'CSC 221',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 320,
    pages: 10,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T10:00:00.000Z',
  },
  {
    id: 'csc-212',
    title: 'Internet Technologies I',
    courseCode: 'CSC 212',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 476,
    pages: 11,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T09:30:00.000Z',
  },
  {
    id: 'gst-201',
    title: 'Peace Studies & Conflict Resolution',
    courseCode: 'GST 201',
    level: '200 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 710,
    pages: 5,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T09:00:00.000Z',
  },
  {
    id: 'csc-292',
    title: 'Java Programming Lab',
    courseCode: 'CSC 292',
    level: '200 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 615,
    pages: 15,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T10:00:00.000Z',
  },

  // ── 300 LEVEL (15 Papers) ───────────────────────────────────
  {
    id: 'csc-301',
    title: 'Systems Analysis and Design',
    courseCode: 'CSC 301',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 540,
    pages: 9,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T09:00:00.000Z',
  },
  {
    id: 'csc-302',
    title: 'Object-Oriented Analysis & Design',
    courseCode: 'CSC 302',
    level: '300 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 412,
    pages: 11,
    date: '3 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-03T08:30:00.000Z',
  },
  {
    id: 'csc-304',
    title: 'Database Management Systems',
    courseCode: 'CSC 304',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 654,
    pages: 12,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T10:00:00.000Z',
  },
  {
    id: 'csc-305',
    title: 'Operating Systems',
    courseCode: 'CSC 305',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 490,
    pages: 10,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T09:30:00.000Z',
  },
  {
    id: '3',
    title: 'Internet Communication and Architecture',
    courseCode: 'CSC 315',
    level: '300 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 642,
    pages: 12,
    date: '1 week ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: 'csc-308-web-design-programming',
    title: 'Web Design and Programming',
    courseCode: 'CSC 308',
    level: '300 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 1205,
    pages: 14,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Web%20Design%20and%20Programming.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T10:00:00.000Z',
  },
  {
    id: 'csc-310',
    title: 'Compiler Construction',
    courseCode: 'CSC 310',
    level: '300 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 298,
    pages: 13,
    date: '3 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-16T09:30:00.000Z',
  },
  {
    id: 'csc-311',
    title: 'Theory of Computation',
    courseCode: 'CSC 311',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 304,
    pages: 8,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T10:00:00.000Z',
  },
  {
    id: 'csc-312',
    title: 'Software Engineering',
    courseCode: 'CSC 312',
    level: '300 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 620,
    pages: 12,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T09:30:00.000Z',
  },
  {
    id: 'csc-316',
    title: 'Computer Networks I',
    courseCode: 'CSC 316',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 543,
    pages: 10,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T09:00:00.000Z',
  },
  {
    id: 'csc-321',
    title: 'Algorithms & Complexity Analysis',
    courseCode: 'CSC 321',
    level: '300 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 415,
    pages: 11,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T11:00:00.000Z',
  },
  {
    id: 'csc-322',
    title: 'Structured Programming',
    courseCode: 'CSC 322',
    level: '300 Level',
    year: '2022/2023',
    semester: '2nd Semester',
    downloads: 300,
    pages: 9,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T10:30:00.000Z',
  },
  {
    id: 'csc-331',
    title: 'Computer Architecture',
    courseCode: 'CSC 331',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 310,
    pages: 10,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T10:00:00.000Z',
  },
  {
    id: 'csc-341',
    title: 'Research Methods in CS',
    courseCode: 'CSC 341',
    level: '300 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 280,
    pages: 7,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T15:00:00.000Z',
  },
  {
    id: 'csc-399',
    title: 'Industrial Training (SIWES)',
    courseCode: 'CSC 399',
    level: '300 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 940,
    pages: 15,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T14:30:00.000Z',
  },

  // ── 400 LEVEL (15 Papers) ───────────────────────────────────
  {
    id: 'csc-401',
    title: 'Artificial Intelligence',
    courseCode: 'CSC 401',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 712,
    pages: 11,
    date: 'Recently added',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-05T19:00:00.000Z',
  },
  {
    id: 'csc-402',
    title: 'Computer Graphics & Visualization',
    courseCode: 'CSC 402',
    level: '400 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 504,
    pages: 13,
    date: 'Recently added',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Web%20Design%20and%20Programming.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-05T18:30:00.000Z',
  },
  {
    id: '2',
    title: 'Data Mining and Warehouse',
    courseCode: 'CSC 411',
    level: '400 Level',
    year: '2022/2023',
    semester: '2nd Semester',
    downloads: 512,
    pages: 10,
    date: '5 days ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-06-01T10:00:00.000Z',
  },
  {
    id: 'csc-404',
    title: 'Distributed Computing Systems',
    courseCode: 'CSC 404',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 418,
    pages: 12,
    date: '1 week ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-30T10:30:00.000Z',
  },
  {
    id: 'csc-405',
    title: 'Cryptography & Network Security',
    courseCode: 'CSC 405',
    level: '400 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 625,
    pages: 10,
    date: '1 week ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: 'csc-412',
    title: 'Special Topics in Computer Science',
    courseCode: 'CSC 412',
    level: '400 Level',
    year: '2022/2023',
    semester: '1st Semester',
    downloads: 240,
    pages: 8,
    date: '2 weeks ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/COMPUTER%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-23T10:00:00.000Z',
  },
  {
    id: 'csc-415-wireless-communication',
    title: 'Wireless Communication',
    courseCode: 'CSC 415',
    level: '400 Level',
    year: '2022/2023',
    semester: '2nd Semester',
    downloads: 730,
    pages: 9,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T10:00:00.000Z',
  },
  {
    id: 'csc-416',
    title: 'Computer Networks II',
    courseCode: 'CSC 416',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 485,
    pages: 10,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Wireless%20Communication.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T09:30:00.000Z',
  },
  {
    id: 'csc-421',
    title: 'Neural Networks & Deep Learning',
    courseCode: 'CSC 421',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 590,
    pages: 14,
    date: '1 month ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-05-06T09:00:00.000Z',
  },
  {
    id: 'csc-422',
    title: 'Human-Computer Interaction',
    courseCode: 'CSC 422',
    level: '400 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 382,
    pages: 11,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Web%20Design%20and%20Programming.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T10:00:00.000Z',
  },
  {
    id: 'csc-425',
    title: 'Soft Computing',
    courseCode: 'CSC 425',
    level: '400 Level',
    year: '2022/2023',
    semester: '2nd Semester',
    downloads: 295,
    pages: 9,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/OBJECT%20ORIENTED%20PROGRAMMING.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T09:30:00.000Z',
  },
  {
    id: 'csc-431',
    title: 'Cloud Computing & Microservices',
    courseCode: 'CSC 431',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 620,
    pages: 12,
    date: '2 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Internet%20Communication%20and%20Architecture.docx',
    uploadedBy: 'system',
    createdAt: '2026-04-20T09:00:00.000Z',
  },
  {
    id: 'csc-441',
    title: 'Big Data Analytics',
    courseCode: 'CSC 441',
    level: '400 Level',
    year: '2023/2024',
    semester: '1st Semester',
    downloads: 510,
    pages: 15,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Data%20Mining%20and%20Warehouse.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T10:00:00.000Z',
  },
  {
    id: 'csc-451',
    title: 'Mobile Application Development',
    courseCode: 'CSC 451',
    level: '400 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 690,
    pages: 13,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Web%20Design%20and%20Programming.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T09:30:00.000Z',
  },
  {
    id: 'csc-499',
    title: 'Final Year Project Guide',
    courseCode: 'CSC 499',
    level: '400 Level',
    year: '2023/2024',
    semester: '2nd Semester',
    downloads: 1450,
    pages: 16,
    date: '3 months ago',
    type: 'Past Question',
    status: 'published',
    facultyId: 'science',
    departmentId: 'computer-science',
    fileUrl: '/papers/Advance%20System%20and%20Designs.docx',
    uploadedBy: 'system',
    createdAt: '2026-03-15T09:00:00.000Z',
  }
];
